// Prisma 5 configuration
// Configuration is primarily in prisma/schema.prisma
// This file is kept for compatibility but not required
export default {};

// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
// import { defineConfig, env } from "prisma/config";

// export default defineConfig({
//   schema: "src/prisma/schema.prisma",
//   migrations: {
//     path: "src/prisma/migrations",
//   },
//   datasource: {
//     url: env("DATABASE_URL"),
//   },
// });
